### ISSUE TITLE
[Edit] CSS : Animations

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#438]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Make changes in this file: **content/css/concepts/animations/animations.md**

Let's change the `@keyframes` rule to better demonstrate how CSS animations allow for multiple style changes to be implemented at different points in the frame-to-frame transition. Something like:

```css
@keyframes color-change {
  from {
    color: purple;
  }
  25% {
    color: yellow;
  }
  50% {
    color: red;
  }
  75% {
    color: blue;
  }
  to {
    color: yellow:
  }
}
```

And then, in the `h1` selector, let's change the `color` value to `purple`.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Assignee(s) added
